language: ruby
rvm: 2.2.5
sudo: false
dist: trusty
branched:
  except:
    - master
install:
 - gem install jekyll jekyll-paginate
 - nvm install 6.1
 - nvm use 6.1
 - npm install
script: npm run test