sudo: required
before_install:
 - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
 - sudo apt-get update -q
 - sudo apt-get install -y ruby build-essential nodejs git
 - sudo gem install jekyll jekyll-paginate

script: npm test