# Site settings
title: RIT Electric Vehicle Team
email: evt@rit.edu
description: > 
  Official website for the RIT Electric Vehicle Team. Check here for news, info,
  and sponsorship information.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://evt.rit.edu" # the base hostname & protocol for your site

permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown

paginate: 5
gems: [jekyll-paginate]

collections:
  projects:
    output: true
